server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp #tcp kafka rocketMQ rabbitMQ
  flatMessage: true
  zookeeperHosts:
  syncBatchSize: 1000
  retries: -1
  timeout:
  accessKey:
  secretKey:
  consumerProperties:
    canal.tcp.server.host: canal-server:11111
    canal.tcp.zookeeper.hosts:
    canal.tcp.batch.size: 500
    canal.tcp.username:
    canal.tcp.password:

  srcDataSources:
    big_market_01:
      url: jdbc:mysql://mysql:3306/big-market-01?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=false
      username: canal
      password: canal
      driver-class-name: com.mysql.jdbc.Driver  # MySQL JDBC driver class
    big_market_02:
      url: jdbc:mysql://mysql:3306/big-market-02?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=false
      username: canal
      password: canal
      driver-class-name: com.mysql.jdbc.Driver  # MySQL JDBC driver class

  canalAdapters:
  - instance: example # canal instance Name or mq topic name
    groups:
    - groupId: g1
      outerAdapters:
      - name: logger
      - name: es7
        hosts: elasticsearch:9200 # 127.0.0.1:9200 for rest mode
        properties:
          mode: rest # transport or rest
          cluster.name: docker-cluster

# Add the logging configuration here
logging:
  level:
    root: DEBUG